# frozen_string_literal: true

source 'https://rubygems.org'

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

gem 'amazing_print', '~> 1.4.0'

gem 'bunny', '~> 2.19'
gem 'dry-initializer', '~> 3.0.3'
gem 'dry-validation', '~> 1.5.0'

gem 'puma', '~> 5.5'
gem 'rack-contrib', '~> 2.3'
gem 'rack-ougai', '~> 0.2.1'
gem 'rack-request-id', '~> 0.0.4'
gem 'rake', '~> 13.0'

gem 'sinatra', '~> 2.1', require: 'sinatra/base'
gem 'sinatra-contrib', '~> 2.1'

gem 'config', '~> 2.2'
gem 'i18n', '~> 1.8'
gem 'jwt', '~> 2.2.1'
gem 'pry', '~> 0.14'

gem 'pg', '~> 1.2'
gem 'sequel', '~> 5.32.0'
gem 'sequel_secure_password', '~> 0.2.15'
gem 'sequel-seed', '~> 1.1'

gem 'activesupport', '~> 6.1'

group :test do
  gem 'database_cleaner-sequel', '~> 1.8'
  gem 'factory_bot', '~> 5.2'
  gem 'faker', '~> 2.19'
  gem 'rack-test', '~> 1.1'
  gem 'rspec', '~> 3.9'
end
