filebeat:
  inputs:
    - type: log
      json:
        message_key: message
        keys_under_root: true
    - paths:
      - /var/lib/docker/containers/*/*.log
      json:
        message_key: message
        keys_under_root: true
  processors:
    - drop_fields:
        fields: ["uuid", "token", "password", "session_uuid"]
        ignore_missing: true
setup:
  kibana:
    host: "http://10.0.0.170:5601"
output:
  elasticsearch:
    hosts: "http://10.0.0.36:9200"