# frozen_string_literal: true

source 'https://rubygems.org'

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

gem 'amazing_print', '~> 1.4.0'

gem 'bunny', '~> 2.19'

gem 'dry-initializer', '~> 3.0.3'
gem 'dry-validation', '~> 1.5.0'

gem 'faraday', '~> 1.0.1'
gem 'faraday_middleware', '~> 1.0.0'

gem 'puma', '~> 5.5'
gem 'rack-contrib', '~> 2.3'
gem 'rack-ougai', '~> 0.2.1'
gem 'rack-request-id', '~> 0.0.4'
gem 'rake', '~> 13.0'

gem 'sinatra', '~> 2.1', require: 'sinatra/base'
gem 'sinatra-contrib', '~> 2.1'

gem 'config', '~> 2.2'
gem 'i18n', '~> 1.8'
gem 'pry', '~> 0.14'


group :test do
  gem 'rack-test', '~> 1.1'
  gem 'rspec', '~> 3.9'
end
