db:
  database: ms-auth
  host: <%= ENV.fetch('DATABASE_HOST') %>
  user: <%= ENV.fetch('PG_USER') %>
  password: <%= ENV.fetch('PG_PASSWORD') %>
app:
  secret: <%= ENV.fetch('APP_SECRET') %>
rabbit_mq:
  host: <%= ENV.fetch('RABBITMQ_HOST') %>
  username: <%= ENV.fetch('RABBITMQ_USER') %>
  password: <%= ENV.fetch('RABBITMQ_PASSWORD') %>