---
- name: ensure trusted key is added
  apt_key:
    url: 'https://download.docker.com/linux/ubuntu/gpg'
    state: present
- name: ensure docker repository is added
  apt_repository:
    repo: 'deb https://download.docker.com/linux/ubuntu bionic stable'
    state: present
- name: ensure packages are installed
  apt:
    name: '{{ item }}'
  with_items:
    - 'ca-certificates'
    - 'curl'
    - 'gnupg'
    - 'lsb-release'
- name: ensure docker is installed
  apt:
    name: '{{ item }}'
  with_items:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - python3-docker