default: &default
  adapter: postgresql
  pool: 5
  username: <%= ENV.fetch('PG_USER') %>
  password: <%= ENV.fetch('PG_PASSWORD') %>
  host: <%= ENV.fetch('DATABASE_HOST') %>
  
development:
  <<: *default
  database: ms-ads-dev

test:
  <<: *default
  database: ms-ads-test

production:
  <<: *default
  database: ms-ads-production